In [30]:
import numpy as np
import random

In [82]:
#reshape 함수를 사용해 1부터 30까지의 숫자 중 짝수를 찾아 (3,5)의 행렬로 만드시오.
a = np.arange(2,30+1,2)
b= a.reshape(3,5)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [83]:
b= a.reshape(3,5)
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [81]:
#np.random.randint(1, 45, (3,4))를 출력하고 리스트 형태로 변환하여 출력하시오.
a = np.random.randint(1, 45, (3,4))
b=[]


array([[36, 39, 28, 16],
       [14, 33, 23, 22],
       [41, 35, 36,  1]], dtype=int32)

In [77]:
#문제: 아래 배열을 3행 4열 형태로 reshape 하시오. 변환된 배열에서 마지막 행만 출력하시오
datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]]
arr = np.array(datas)
arr2d = arr.reshape(3, 4)
arr2d
print(

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [65]:
#코드와 그  출력값이 다음과 같을 때 0.6664104711248381을 출력하는 코드를 작성하시오.
random.seed(12)
print(random.random())
print(random.random())
print(random.random())
print(random.random())

0.4745706786885481
0.6574725026572553
0.6664104711248381
0.14260035292536777


In [70]:
#seed값을 5로 고정한 후 random.randint(1,11)을 세번 실행했을 때 나오는 값을 구하시오
random.seed(12)
print(random.randint(1,11))
print(random.randint(1,11))
print(random.randint(1,11))

8
5
11


In [88]:
#10부터 30까지 정수로 이루어진 1차원배열을 만든다음 2차원  (7, -1) 형태로 변환하시오
a = np.arange(10, 30+1)
b= a.reshape(7,-1)
print(b.max())
print(b.min())

30
10


In [96]:
#(1) 1~25까지 step이 3개인 1차원의 배열을 만들고,
#(2) reshape을 이용하여 3x3행렬로 만드시오.
a = np.arange(1,26,3)
b = a.reshape(3,3)
b

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [ ]:
# slicing 문제 : 다음의 데이터를 추철하는 하는 코드를 작성하시오
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]

In [101]:
# numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고, 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.
a = (np.arange(1,11,2)
b = (np.arange(2.11,2)
list_name = [a,b]
list_name

[[np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9)], []]

In [ ]:
np.random.randint(1, 45, (3,4))를 출력하고 리스트 형태로 변환하여 출력하시오.

In [20]:
#range을 이용하여 1~20까지 숫자를 나열한 후 4행 5형로 정렬하고 그 중 각 행의 최소값을 추출

In [41]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
b = arr.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
b.min(axis=1)

array([ 1,  6, 11, 16])