In [1]:
import numpy as np

In [6]:
np.__version__

'2.2.6'

# numpy 객체 생성

In [14]:
#리스트 ->ndarray
a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [24]:
type(arr)

numpy.ndarray

In [22]:
len(arr)

5

In [19]:
#튜플 ->ndarray
a = (1,2,3,4,5)
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [21]:
arr.size

5

In [23]:
arr.dtype

dtype('int64')

In [27]:

a = ['a',2,3,4,5]
arr = np.array(a)
arr

array(['a', '2', '3', '4', '5'], dtype='<U21')

In [28]:
a = [1.0,2,3,4,5]
arr = np.array(a)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
# 2차원 데이터 만들기

In [31]:
a2d = [[1, 3, 2], [5, 4, 7], [4, 6, 9]] 
a2d

[[1, 3, 2], [5, 4, 7], [4, 6, 9]]

In [32]:
type(a2d)

list

In [34]:
arr2d = np.array(a2d)
arr2d

array([[1, 3, 2],
       [5, 4, 7],
       [4, 6, 9]])

In [36]:
# array의 전체 요소의 갯수
arr2d.size

9

In [38]:
arr2d

array([[1, 3, 2],
       [5, 4, 7],
       [4, 6, 9]])

In [39]:
np.save('my_array', arr2d)

In [41]:
arr2d = np.load('my_array.npy')
arr2d

array([[1, 3, 2],
       [5, 4, 7],
       [4, 6, 9]])

# Built in은 넘파이 내장함수

In [43]:
np.zeros(4)

array([0., 0., 0., 0.])

In [44]:
np.zeros((2,4,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [45]:
#1차원
np.ones((7,))

array([1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.full((7,),5)

array([5, 5, 5, 5, 5, 5, 5])

In [48]:
np.full((7,2), 5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [49]:
np.full((4,2,3),5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [50]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(5, 30+1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [58]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [60]:
arr = np.arange(1,21+1)

In [62]:
arr2d = arr.reshape(3,7)
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [63]:
arr2d.shape

(3, 7)

In [68]:
arr1d = arr.reshape(7,3)
arr1d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [69]:
arr1d.shape

(7, 3)

In [72]:
arr2d = arr1d.reshape(-1,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [74]:
arr2d.max()

np.int64(21)

In [75]:
arr2d.min()

np.int64(1)

In [76]:
arr2d.sum()

np.int64(231)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [78]:
arr.mean()

np.float64(11.0)

In [79]:
print(arr.std())

6.0553007081949835


In [80]:
arr.var()

np.float64(36.666666666666664)

In [82]:
a = np.arange(5,20)
a.size

15

In [83]:
a.reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
np.arange(5,20).reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
#랜덤값으로 채워진 배열을 만들 수 있다

In [86]:
import random

In [88]:
random.random()

0.6461210339357781

In [89]:
np.random.random(5)

array([0.80282574, 0.36112619, 0.65133506, 0.1534736 , 0.23594767])

In [90]:
np.random.random((5,))

array([0.04399801, 0.6094947 , 0.2421639 , 0.89612015, 0.37654115])

In [93]:
np.random.random((3,5))

array([[0.38128894, 0.33749134, 0.23004371, 0.67228013, 0.33754572],
       [0.25861619, 0.2974837 , 0.55206661, 0.14609938, 0.98106875],
       [0.53678133, 0.32244196, 0.86967935, 0.27543951, 0.52472407]])

In [104]:
random.seed(4)
random.random()

0.23604808973743452

In [99]:
random.random()

0.396058242610681

In [100]:
np.random.seed(3)

In [105]:
np.random.random((3,5))

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [106]:
np.random.random((3,5))

array([[0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774, 0.54464902],
       [0.78031476, 0.30636353, 0.22195788, 0.38797126, 0.93638365]])

In [107]:
np.random.seed(9)

In [108]:
np.random.randint(1,45,(7,))

array([29, 23,  2, 23, 41, 28, 34], dtype=int32)

In [109]:
np.random.randint(1,45,(3,4))

array([[30, 29,  1, 25],
       [11, 30, 43, 13],
       [19, 23,  2, 36]], dtype=int32)

In [110]:
X = np.random.randint(1,100,(3,4))

In [111]:
X.max()

np.int32(81)

In [112]:
X.min()

np.int32(10)

In [113]:
X.mean()

np.float64(41.583333333333336)

In [114]:
X.std()

np.float64(22.687949567018073)

In [115]:
X.var()

np.float64(514.7430555555555)

In [117]:
a =np.array([3,4,5,6,7,8,9,10])
sorted(a.tolist())

[3, 4, 5, 6, 7, 8, 9, 10]

In [118]:
np.random.seed(3)
X = np.random.randint(1, 100, (4,5))
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [121]:
X.max(axis=0)
X.max(axis=1)

array([73, 75, 97, 94], dtype=int32)

In [137]:
# np.arange(start, stop, step)
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [140]:
arr = np.arange(1,31+1)
arr2d = arr.reshape(3, 10)

ValueError: cannot reshape array of size 31 into shape (3,10)

In [147]:
arr_a = array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

NameError: name 'array' is not defined

In [149]:
arr_a = np.arange(1, 12 + 1)
arr_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [151]:
arr_b = arr_a.reshape(2, 6)
arr_b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [153]:
result_array = arr_b.reshape(4, -1)
result_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])